// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbEstadosDelPedido
    {
        public int estp_Id { get; set; }
        public string estp_Nombre { get; set; }
        public int estp_UsuCreacion { get; set; }
        public bool estp_Habilitado { get; set; }
        public string estp_Visible { get; set; }
        public string user_Creacion { get; set; }
        public DateTime? estp_FechaCreacion { get; set; }
        public int? estp_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? estp_FechaModificacion { get; set; }
        public bool? estp_Estado { get; set; }
    }
}