// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbEscalasPorTrayecto
    {
        public int estr_Id { get; set; }
        public int tray_Id { get; set; }
        public int muni_Escala { get; set; }
        public int estr_UsuCreacion { get; set; }
        public DateTime? estr_FechaCreacion { get; set; }
        public int? estr_UsuModificacion { get; set; }
        public DateTime? estr_FechaModificacion { get; set; }
        public bool? estr_Estado { get; set; }
        public string user_Creacion { get; set; }
        public string user_Modificacion { get; set; }
    }
}