// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbMunicipios
    {
        public string muni_Id { get; set; }
        public string muni_Nombre { get; set; }
        public string muni_Id { get; set; }
        public string depa_Id { get; set; }
        public string depa_Nombre { get; set; }
        public int muni_UsuCreacion { get; set; }
        public bool muni_Habilitado { get; set; }
        public string muni_Visible { get; set; }
        public string user_Creacion { get; set; }
        public DateTime muni_FechaCreacion { get; set; }
        public int? muni_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? muni_FechaModificacion { get; set; }
        public bool muni_Estado { get; set; }
    }
}