// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbMarcas
    {
        public int marc_Id { get; set; }
        public string marc_Nombre { get; set; }
        public bool marc_Habilitado { get; set; }
        public string marc_Visible { get; set; }
        public int marc_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime? marc_FechaCreacion { get; set; }
        public int? marc_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }
        public bool? marc_Estado { get; set; }
    }
}