// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbMetodosdePago
    {
        public int meto_Id { get; set; }
        public string meto_Descripcion { get; set; }
        public bool meto_Habilitado { get; set; }
        public string meto_Visible { get; set; }
        public int meto_UsuCreacion { get; set; }
        public string user_Creacion { get; set; }
        public DateTime? meto_FechaCreacion { get; set; }
        public int? meto_UsuModificacion { get; set; }
        public string user_Modificacion { get; set; }
        public DateTime? meto_FechaModificacion { get; set; }
        public bool? meto_Estado { get; set; }
    }
}