// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbPedidos
    {
        public int pedi_Id { get; set; }
        public int clie_Id { get; set; }
        public int muni_Origen { get; set; }
        public int muni_Destino { get; set; }
        public string pedi_DestinoFinal { get; set; }
        public int estp_Id { get; set; }
        public int pedi_UsuCreacion { get; set; }
        public DateTime? pedi_FechaCreacion { get; set; }
        public int? pedi_UsuModificacion { get; set; }
        public DateTime? pedi_FechaModificacion { get; set; }
        public bool? pedi_Estado { get; set; }
        public string user_Creacion { get; set; }
        public string user_Modificacion { get; set; }
    }
}