// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FletesNacionales.Entities.Entities
{
    public partial class VW_tbModelos
    {
        public int mode_Id { get; set; }
        public string mode_Nombre { get; set; }
        public bool mode_Habilitado { get; set; }
        public string mode_Visible { get; set; }
        public int marc_Id { get; set; }
        public string marc_Nombre { get; set; }
        public int tipv_Id { get; set; }
        public string tipv_Descripcion { get; set; }
        public int mode_UsuCreacion { get; set; }
        public DateTime? mode_FechaCreacion { get; set; }
        public int? mode_UsuModificacion { get; set; }
        public DateTime? mode_FechaModificacion { get; set; }
        public bool? mode_Estado { get; set; }
        public string user_Creacion { get; set; }
        public string user_Modificacion { get; set; }
    }
}